workflows:
  ios-workflow:
    name: iOS Dev Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios-signing:
        development:
          team_id: REPLACE_WITH_YOUR_TEAM_ID
          email: $APP_STORE_CONNECT_EMAIL
          password: $APP_STORE_CONNECT_PASSWORD
    scripts:
      - flutter pub get
      - flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
