workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Build IPA
        script: |
          xcodebuild -scheme IPAGURUApp -configuration Release -sdk iphoneos -archivePath $CM_BUILD_DIR/IPAGURU.xcarchive archive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/IPAGURU.xcarchive -exportPath $CM_BUILD_DIR -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.app.dSYM.zip
