workflows:
  ios-workflow:
    name: iOS Dev Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios-signing:
        automatic:
          team_id: REPLACE_WITH_YOUR_TEAM_ID
    scripts:
      - flutter pub get
      - flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
